kind: Secret
apiVersion: v1
metadata:
  labels:
    {{- include "edms-analyzer.labels" . | nindent 4 }}
  name: {{ template "edms-analyzer.fullname" . }}-env
type: Opaque
data:
  MAYAN_EDMS_USER: {{ .Values.mayanEdms.user | b64enc | quote }}
  MAYAN_EDMS_PASSWORD: {{ .Values.mayanEdms.password | b64enc | quote }}
