kind: Secret
apiVersion: v1
metadata:
  labels:
    {{- include "mayan-edms.labels" . | nindent 4 }}
  name: {{ template "mayan-edms.fullname" . }}-env
type: Opaque
data:
  MAYAN_CELERY_BROKER_URL: redis://:{{ .Values.redis.password }}@{{ template "mayan-edms.redis.host" . }}:{{ .Values.redis.redisPort }}/0
  MAYAN_CELERY_RESULT_BACKEND: redis://:{{ .Values.redis.password }}@{{ template "mayan-edms.redis.host" . }}:{{ .Values.redis.redisPort }}/1
  MAYAN_DATABASES: |
    {'default':{'ENGINE':'django.db.backends.postgresql','NAME':'{{ .Values.postgresql.postgresDatabase }}','PASSWORD':'{{ .Values.postgresql.postgresPassword }}','USER':'{{ .Values.postgresql.postgresUser }}','HOST':'{{ template "mayan-edms.postgresql.host" . }}'}}
