apiVersion: v2
name: mayan-edms
description: Mayan EDMS
type: application
version: 0.1.0
appVersion: 3.3.13
keywords:
  - edms
  - dms
  - mayan-edms
home: https://mayan-edms.com/
icon: https://mayan-edms.com/favicon.ico
sources:
  - https://github.com/mayan-edms/Mayan-EDMS
maintainers:
  - name: joekhoobyar
    email: fourheads@gmail.com
dependencies:
  - name: postgresql
    version: 8.1.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: redis
    version: 10.5.6
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
